class OwningApp
  # This list is generated by running `Artefact.distinct(:owning_app)` in the
  # console.
  BUSINESS_SUPPORT_FINDER = "businesssupportfinder"
  CALCULATORS = "calculators"
  CALENDARS = "calendars"
  FINDER_API = "finder-api"
  FRONTEND = "frontend"
  LICENCE_FINDER = "licencefinder"
  PLANNER = "planner"
  PUBLISHER = "publisher"
  SMART_ANSWERS = "smartanswers"
  SPECIALIST_PUBLISHER = "specialist-publisher"
  TARIFF = "tariff"
  TRAVEL_ADVICE_PUBLISHER = "travel-advice-publisher"
  WHITEHALL = "whitehall"
end
