language: ruby
rvm:
  - 1.9.2
env:
  - DB=mysql GOVUK_APP_DOMAIN=dev.gov.uk RUBYOPT="-rpsych"
services:
  - mongodb
script:
  - bundle exec rake db:drop db:create db:schema:load
  - bundle exec rake
bundler_args: --without=development
branches:
  except:
    - release
notifications:
  email: false
