apps_with_migrated_tagging:
 - businesssupportfinder
 - calculators
 - calendars
 - licencefinder
 - smartanswers
 - policy-publisher
 - hmrc-manuals-api
 - travel-advice-publisher
 - tariff

apps_without_tagging:
  - finder-api
  - frontend
  - planner
